"""Compatibility import path for canonical public contract identifiers."""

from __future__ import annotations

from pine2ast.contract_ids import (
    AST_CATALOG_CONTRACT,
    CATALOG_SCHEMA_VERSION,
    FRONTEND_CONTRACT,
    SEMANTIC_FACTS_CONTRACT,
    SECTION_CONTRACTS,
    SOURCE_MANIFEST_CONTRACT,
    SUPPORT_PROFILE_CONTRACT,
    TOP_LEVEL_REQUIRED,
)

__all__ = [
    "AST_CATALOG_CONTRACT",
    "CATALOG_SCHEMA_VERSION",
    "FRONTEND_CONTRACT",
    "SOURCE_MANIFEST_CONTRACT",
    "SEMANTIC_FACTS_CONTRACT",
    "SECTION_CONTRACTS",
    "SUPPORT_PROFILE_CONTRACT",
    "TOP_LEVEL_REQUIRED",
]
